# @package _global_
defaults:
  - local: default

data: gittopic
freq_path: ${data_path}/all_topics_freq.csv
reconciled_folder_path: ${data_path}
reconciled_type: reconciled-gittopic
out_path: ${data_path}
disambiguation:
  _target_: processing.disambiguate.FirstCleanDisambiguate
  types_path: ${data_path}/annotated_wikitypes.csv